### PR TITLE
Import Local Field

### PR DESCRIPTION
**Pull request by a-crowell**
### Description
The Import Local Mirabuf panel used to load every file as a robot, now it goes based on the dropdown.

### CODE REVIEW

**Review by Dhruv-0-Arora — APPROVED** [review]
Looks good 👍

As a future task, can we put the import local mira panel into the "spawn asset" modal rather than have it as a stand alone button on the MainHUD.
I also think this UI is a bit funky
Screenshot 2024-07-31 at 12 10 14 PM

**Comment by a-crowell** [comment]
@Dhruv-0-Arora I agree this would be good to merge into Spawn Asset someday. Then we don't have to worry about that UI 👍

**Comment by Dhruv-0-Arora** [comment]
> @Dhruv-0-Arora I agree this would be good to merge into Spawn Asset someday. Then we don't have to worry about that UI 👍

I shall bestow this responsibility upon myself and have it done today 🫡

**Review by LucaHaverty — APPROVED** [review]
LGTM 👍 👍 👍

**Pull request merged**
