### PR TITLE
Main HUD Improvements

### PR DESCRIPTION
**Pull request by PepperLola**
### Description
Improved the main HUD to fit with the Figma design, including a gradient background, the Autodesk logo, two separated buttons, and two item trays. The color manager sets the colors, so the default color scheme should be updated later. The hover effect in Figma is a lighter color than the background, but I don't think that's possible with the built-in color tint transition for Unity buttons. Luca is working on something that would make this possible, so I will update that once his is merged.

Screenshot 2023-07-20 at 4 54 06 PM

### Objectives
- [X] Updated Main HUD design
- [X] Item hover effect
- [X] Open and close HUD *(tween library breaks sometimes and causes the movement to not happen)*
- [X] Update entries in practice mode
- [X] Update entries in match mode

### Testing Done
- Entered in modes available from main menu
- Clicked buttons to make sure modals/panels appear
- Change colors in theme manager
- Open and close a lot (after restarting Unity so tween library works)

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1575)

### CODE REVIEW

**Review by Markytt — CHANGES_REQUESTED** [review]
When I try to spawn in a robot using spawn assets or MultiBot, error messages will appear and the modal will appear without a dropdown. 
Screenshot 2023-07-20 090430

Also if you try to click cancel on the model to make it disappear, an error message will appear saying that the modal failed to be closed. 
Screenshot 2023-07-20 090500

**Review by a-crowell — CHANGES_REQUESTED** [review]
Looking good. When you open a modal the open icon is still an X though. Same functionality, just the icon.

image

**Comment by PepperLola** [comment]
I moved controls and settings out of config mode because those have global options and I think they should be accessible without having a robot loaded.

**Comment by a-crowell** [comment]
> I moved controls and settings out of config mode because those have global options and I think they should be accessible without having a robot loaded.

@KyroVibe We talked about this and I agree with taking it out if you've changed your mind.

**Review by LucaHaverty — CHANGES_REQUESTED** [review]
It looks great!

Couple things I noticed:

If you change the "interactive select" color, it does not update until you stop Unity and hit play again.

If you quit to the main menu, then save the theme editor in the main menu, then enter singleplayer again, the main HUD shows up like this before choosing a mode:

image

I also noticed that the button highlights are smaller than in figma. Additionally, the icons and text seem to be closer to the edge and to each other in figma. It looks like the figma version is shorter overall.
image

image


Also, you might want to add a new color for the main hud buttons background because it is different than the new panel and modal bg color.

I have not found any issues with it's functionality. Just these small changes and it should be good to go!

**Review by a-crowell — CHANGES_REQUESTED** [review]
Nice job changing the robot when you moved Controls. Couple bugs: When you spawn and remove a robot in practice mode, it brings up errors that keep you from continuing (images below). In match mode, it shows the controls of the first robot you clicked controls on instead of the selected one. To avoid these, what if we separated the controls into global and robot?

image
image


Do we want users to be able to spawn in match mode and/or config mode? Config mode seems to work fine and match mode would just need a little work with the robot moving wherever you click, but we could also remove them. Especially with config mode, the top button could become the back button.

Personally, I think we should remove spawning from match mode and leave it to the set up at the beginning. Maybe later, that top button could become a pause or reset. For config mode, I like the idea of the back button being at the top and don't have a strong opinion for keeping spawn in an item tray (except match mode) or completely removing it.

**Review by a-crowell — APPROVED** [review]
Great work!

**Review by BrandonPacewic — COMMENTED** [review]
Looks good. I noticed a small `x` on the bottom of the screen, not sure if it's related to this pr or not but it doesn't seem to be on `dev`.

Screenshot 2023-07-21 at 11 36 51 AM copy

**Comment by LucaHaverty** [comment]
> Looks good. I noticed a small `x` on the bottom of the screen, not sure if it's related to this pr or not but it doesn't seem to be on `dev`.
> 
> Screenshot 2023-07-21 at 11 36 51 AM copy

Pretty sure that's from the old toast system

**Review by LucaHaverty — COMMENTED** [review]
I didn't find any issues with how it works, nice job! I'm not a huge fan of how the button to collapse it is so far above the main hud though (especially in match mode). I think that users might not see it or not make the connection of what it is for. It is also hard to see against the background. Is there any way it could be part of the main hud or at least feel like they are related?

image

**Review by KyroVibe — CHANGES_REQUESTED** [review]
Pretty much perfect. I would be a little concerned about players not know what to do if they were dropped into the sim without a robot or field and has the MainHUD collapsed but we can see about that with the beta. I would switch to use the new Tweening system because when I was testing the current one failed.

**Review by Markytt — COMMENTED** [review]
Things seem to be working well, the only bug I found was that in match mode, the controls shown sometimes still don't match the controls of the currently selected robot.

**Comment by PepperLola** [comment]
> Things seem to be working well, the only bug I found was that in match mode, the controls shown sometimes still don't match the controls of the currently selected robot.

Could you provide steps to reproduce this issue, and do you know if there's something specific that happens to trigger that or is it just random?

**Comment by PepperLola** [comment]
> I didn't find any issues with how it works, nice job! I'm not a huge fan of how the button to collapse it is so far above the main hud though (especially in match mode). I think that users might not see it or not make the connection of what it is for. It is also hard to see against the background. Is there any way it could be part of the main hud or at least feel like they are related?
> 
> image

I just recreated the way it looks in Figma. The skybox in that design was dark which made it easier to see, so maybe we could change the color of the icons later?

**Comment by PepperLola** [comment]
> Looks good. I noticed a small `x` on the bottom of the screen, not sure if it's related to this pr or not but it doesn't seem to be on `dev`.
> Screenshot 2023-07-21 at 11 36 51 AM copy

This was from the old toast system and is gone now with the new one.

**Review by KyroVibe — APPROVED** [review]
Looks good!

**Review by BrandonPacewic — APPROVED** [review]
Clean recreation of the new design!

**Review by LucaHaverty — APPROVED** [review]
Looks good, fantastic work!

**Review by Markytt — APPROVED** [review]
The code is working great, I didn't find anymore issues or bugs.

**Pull request merged**
