### PR TITLE
Fix analytics by using client ID instead of user ID and update GUID generation

### PR DESCRIPTION
**Pull request by wangl5**
- Use client ID instead of user ID as hits with a user ID were not showing up in the analytics dashboard
- Use randomly generated user ID instead of the hash of the username

|    DOD    | Done |    Reviewer    | Issue | Notes |
|-----------|------|----------------|-------|-------|
| Code      | ❌   |Kira Corbett|  1079|       |
| Unit Test | N/A  | N/A            |       |       |
| Merged    | ❌  |                |       |       |

### CODE REVIEW

**Comment by victoryforphil** [comment]
Wont this generate a new GUID on each run? Removing all user tracking? IIRC the user id was working fine in the dashboard.

**Comment by KiraCorbett** [comment]
I think we have to generate a new GUID so that we are not tracking personal clients.

**Comment by wangl5** [comment]
@victoryforphil The GUID is saved to the settings XML file so it isn't reset each run. The user id hash version worked but was only anonymous one way. If someone's username is known, it is possible to hash the username and see their corresponding analytics.

**Comment by victoryforphil** [comment]
If the GUID is saved then that's a good compromise.

**Comment by wangl5** [comment]
@victoryforphil 
> IIRC the user id was working fine in the dashboard.

The hits were showing up in the realtime dashboard view but they didn't show up in the `Audience` or `Behavior` tabs for me. Are you sure you saw the hits in either of those tabs?

**Comment by KiraCorbett** [comment]
@wangl5 Is this okay to merge? I checked the dashboard this morning and saw some user hits on various pages in the Behavior > Site Content section as well as Audience > User Explorer.

**Comment by wangl5** [comment]
> @wangl5 Is this okay to merge? I checked the dashboard this morning and saw some user hits on various pages in the Behavior > Site Content section as well as Audience > User Explorer.

@KiraCorbett Yes, this is ready to merge

**Pull request merged**
