### PR TITLE
engine-code-clean branch additions

### PR DESCRIPTION
**Pull request by rasberrypai**
manually added changes from engine-code-clean into master

### CODE REVIEW

**Comment by KiraCorbett** [comment]
@BradenMccoy It might be good to stress test and verify that the UI components are there. 

1. The "x" buttons on help menus
2. Replay Mode UI (and similar spawning UI) icons highlighting are even 
3. Reset field works

**Comment by BradenMccoy** [comment]
[AARD-928](https://jira.autodesk.com/browse/AARD-928)

**Comment by KiraCorbett** [comment]
@BradenMccoy Fixed [AARD-930](https://jira.autodesk.com/browse/AARD-930?filter=-2) and [AARD-929](https://jira.autodesk.com/browse/AARD-929?filter=-2)

**Comment by BradenMccoy** [comment]
AARD-930 and AARD-929 confirmed

**Pull request merged**
