### PR TITLE
Tooltips

### PR DESCRIPTION
**Pull request by LucaHaverty**
### Description
A system to show tooltips at the top center of the screen to show users what certain keys do. Tooltips are a  dynamic panel with a timeout. If one is opened while another is already open, the old one will be closed. The static tooltip manager class is used to create tooltips and manage the timeout. 

### Tooltips list
- Match mode robot placement controls
- Robot controls (drivetrain, pickup, eject)
- Camera controls

### Objectives
- [x] Tooltip system
- [x] Added in all of the tooltips we want

### Testing Done
- Checked spacing with different numbers of tooltips
- Checked spacing with different sizes of tooltips

image
(The visuals will change once this is merged with the modal and panel update)

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1593)

### CODE REVIEW

**Review by a-crowell — CHANGES_REQUESTED** [review]
Looking great! Only thing I saw was tool tips didn't pop up for swerve robots.

**Review by KyroVibe — CHANGES_REQUESTED** [review]
Could you make the tooltips a bit smaller and thinner? They take up quite a bit of the screen space. Also try the horizontal layout (the icon to the right) with a decent amount of spacing

**Comment by LucaHaverty** [comment]
@BrandonPacewic I'm not sure why the formatter failed this time

**Review by a-crowell — APPROVED** [review]
Looks good!

**Review by BrandonPacewic — COMMENTED** [review]
Don't worry about the formatting action. It will be fixed in #904. Just ensure that the auto formatter is run before you merge.

**Review by KyroVibe — APPROVED** [review]
Looks great, useful and non-evasive

**Pull request merged**
