### PR TITLE
Removed Main Menu

### PR DESCRIPTION
**Pull request by KyroVibe**
Yes the title of the branch is off but I did a lot of stuff in this branch.
I:
- Removed main menu from build settings
- Created a grid to be the default "field"
- Removed the help buttons
- Created a settings panel
- Made a new scene that handles the fatal errors
- Made changing the directory for robots and field possible in the sim
- Fixed a quality settings bug

Now this is fine for the Beta but before release we need to:
- Fix the FTC fields because they are below 0
- Re-implement the global updater

Jira Issues completed in this PR:
1046: https://jira.autodesk.com/browse/AARD-1046
1047: https://jira.autodesk.com/browse/AARD-1047
967: https://jira.autodesk.com/browse/AARD-967
597: https://jira.autodesk.com/browse/AARD-597

### CODE REVIEW

**Comment by KyroVibe** [comment]
Changes are made. I will look into the Global versioning checker

**Comment by KyroVibe** [comment]
Ready for PR and Beta

**Comment by KiraCorbett** [comment]
Default bot Dozer spawns too far into the field on first load-in. Everything else looks good!

**Comment by KyroVibe** [comment]
Nearly read for the beta. Just need 905 which I'd rather implement after adding this branch into master due to the fact that this branch is 26 commits ahead of master

**Comment by KiraCorbett** [comment]
@KyroVibe changes look great! Please hold off on merging with master until someone tests final analytics are tested on PR #341.

**Comment by KiraCorbett** [comment]
image

**Comment by HiceS** [comment]
Looked over analytics and it looks good

**Pull request merged**
