### PR TITLE
Toastlogger Using Unity UI

### PR DESCRIPTION
**Pull request by victorxheng**
Comes with the ToastManager script. To call a toast, you write ToastManager.Log("Message");
ToastManager correctly sets up an instance of the ToastLogger with the necessary sprites and manages the showing/disappearing of the scroll rect.

image

Still needs to be merged with the ModuleLoader.

### CODE REVIEW

**Comment by KyroVibe** [comment]
@victorxheng There are two Toast Loggers? One in the UI folder and one in the Scripts folder

**Comment by victorxheng** [comment]
The issues with merging got fixed, and module loader is now able to set the main thread correctly.

image

Uncomment this script out in ToastManager to test the toasts yourself.

**Review by NickBurrell — CHANGES_REQUESTED** [review]
It seems that the `ToastLogger` isn't being registered in `Api.cs`. The line is currently commented out, and likely just needs to be plumbed together.

**Comment by victorxheng** [comment]
@NickBurrell I uncommented it out - is that enough or does anything else need to be done?

**Comment by KyroVibe** [comment]
Rebased branch with master

**Review by KyroVibe — APPROVED** [review]
Switching out the ToastManager is too annoying to do so we'll just leave it in. As long as Logger.Log works we'll be fine.

**Review by NickBurrell — APPROVED** [review]

**Pull request merged**
