### PR TITLE
Saving Gamepiece/Motors/Controls

### PR DESCRIPTION
**Pull request by a-crowell**
### Description
Fix saving in dev, including finding motors in preferences.

If you are still having issues with robot data saving, try deleting and re-downloading robot mira files

### Objectives
- [x] Save Intake and Shot Trajectory Location/Rotation
- [x] Save Controls/Motors

### CODE REVIEW

**Review by Markytt — CHANGES_REQUESTED** [review]
The save doesn't work for positioning the ejector, but besides that, it works for everything else.

**Comment by LucaHaverty** [comment]
> The save doesn't work for positioning the ejector, but besides that, it works for everything else.

Could you send steps to recreate this? I can't seem to

**Review by KyroVibe — CHANGES_REQUESTED** [review]
Encountered error when opening:
```
KeyNotFoundException: The given key 'input/enable_god_mode' was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <130809ae6f984869a6663c878f16e3f3>:0)
System.Collections.ObjectModel.ReadOnlyDictionary`2[TKey,TValue].get_Item (TKey key) (at <130809ae6f984869a6663c878f16e3f3>:0)
GodMode.Update () (at Assets/Scripts/GodMode.cs:58)
```

**Comment by a-crowell** [comment]
> 

Not able to recreate this and, on my laptop, it's putting god mode in the dictionary in `GodMode.Start()` before that line in `Update()`. Could I watch you recreate it with the debugger?

**Review by Markytt — APPROVED** [review]
The ejector issue seems to only be on my computer, and everything else works well.

**Review by KyroVibe — APPROVED** [review]
Seems to work well now. We'll see about that pref issue later. Nice work

**Pull request merged**
