### PR TITLE
Fix critical Inventor exporter crash by reverting JSON changes

### PR DESCRIPTION
**Pull request by wangl5**
Since #298, the Inventor exporter crashes **every time** with the following error when exporting a robot:

Error

This PR reverts #298, removing the JSON bxdj format and fixing the crash.

**NOTE: This only to be merged as a last resort. Ideally, the JSON crash will be fixed without needing to revert.**

|    DOD    | Done |    Reviewer    | Issue | Notes |
|-----------|------|----------------|-------|-------|
| Code      | ❌   | Nicolas Espinoza/Alex Carter |   N/A|       |
| Unit Test | N/A  | N/A            |       |       |
| Merged    | ❌  |                |       |       |

### CODE REVIEW

**Comment by matthew17754** [comment]
Please resolve the merge conflicts

**Comment by wangl5** [comment]
@KiraCorbett @matthew17754 We haven't found a better fix yet so this can be merged after a review.

**Comment by matthew17754** [comment]
Ideally, we wouldn't need to merge this, but if it's necessary, make sure to remove the merge conflicts as well.

**Comment by wangl5** [comment]
@matthew17754 Conflicts resolved. We have not been able to figure out why Alex's changes only work on his machine, so we have agreed that the JSON changes should be reverted (this branch merged) for now since the Inventor exporter in `master` does not function at all. Additionally, the engine on `master` is not able to read the json format since the engine team also reverted their JSON changes afaik.

**Comment by KiraCorbett** [comment]
This builds as a temporary fix for exporters but causes some errors in Unity. Although there are no merge conflicts, it would be good to do an update from master as the current Unity scenes in this branch would override the new scene changes in master.
image

**Comment by wangl5** [comment]
@KiraCorbett Okay, I reverted all PR changes to the unity project.

**Comment by KiraCorbett** [comment]
@KyroVibe Can you take a look at the Unity issues? @wangl5 Thank you for updating with master. Unity builds but now has an older engine bug. It would be good to work with the engine team on resolving that.

**Comment by wangl5** [comment]
@KiraCorbett Are you sure there are still unity issues on the latest `revert-984-exporter-json`? After the latest commits, I am able to run the unity project with no build issues. Also, since there are no longer changes to the unity project in this PR, no additional errors should be introduced.

**Comment by wangl5** [comment]
Bug was temporarily resolved without revert, this branch can be deleted in a few weeks if we don't have any problems with the other fix.

**Pull request closed without merging**
