### PR TITLE
Importing Cached From Map Hotfix

### PR DESCRIPTION
**Pull request by a-crowell**
### Description
Mirabuf files imported from the hashmap would fail to load.

### Objectives
- [X] Load in mirabuf files from hash map
- [X] Removed unused panel
- [X] Fixed generation bug

### Testing
- [X] Forcing hashmap usage on Windows PC
- [x] Safari/Apple Mobile

### CODE REVIEW

**Review by BrandonPacewic — COMMENTED** [review]
> Mirabuf files imported from the hashmap would fail to load.

Any steps to reproduce this bug on `dev`?

**Comment by a-crowell** [comment]
> > Mirabuf files imported from the hashmap would fail to load.
> 
> Any steps to reproduce this bug on `dev`?

On Safari or iOS, try to load a cached mirabuf object.

**Review by Dhruv-0-Arora — CHANGES_REQUESTED** [review]
Talked to Ayla about this: currently on Safari it logs to console "No access to OPFS" and quits without any errors.

**Review by BrandonPacewic — APPROVED** [review]
Works on safari now. Woooooo! 🎊

**Review by Dhruv-0-Arora — APPROVED** [review]
resplendent

**Pull request merged**
