### PR TITLE
928 custom binding fix

### PR DESCRIPTION
**Pull request by KyroVibe**
The gamepiece controls were never properly re-added in a new field. I had a very general fix for it which caused a large bug. I removed the original fix and replaced it with a more precise one that didn't cause the same errors.
Jira issue 928: https://jira.autodesk.com/browse/AARD-928

### CODE REVIEW

**Comment by KiraCorbett** [comment]
@matthew17754 Do you want to test this just to make sure it is not a local issue with key registries?

**Comment by KyroVibe** [comment]
I think it should finally work. PLEASE test extensively before approving. It works just how it should on my computer.

**Comment by KyroVibe** [comment]
@matthew17754 @KiraCorbett

**Comment by KiraCorbett** [comment]
@KyroVibe There was a bug in master so I updated your branch from master. Can you confirm on your end that your branch is behaving as expected? Engine team is testing.

**Comment by KiraCorbett** [comment]
I think we should hold off on merging until we fix a separate Unity bug.

**Pull request merged**
