### PR TITLE
Misc bug fixes

### PR DESCRIPTION
**Pull request by KyroVibe**
- Removed the error thrown by the joint adapters after the joints have been broken.
- Fixed error that was thrown if you tried to select a new entity after deleting one
- Removed triangle count toast

### CODE REVIEW

**Review by KiraCorbett — APPROVED** [review]
Looks good and glad to have the remove entity issue fixed. @KyroVibe Should we make an issue about dealing with broken joints for long term?

**Review by matthew17754 — CHANGES_REQUESTED** [review]
The items in the entity toolbar UI don't gray out after the entity has been deleted. This should be done to indicate that the entity has been deselected.

**Comment by KyroVibe** [comment]
@matthew17754 Well a week later and I'm finally done with the toolbar fix

**Review by matthew17754 — APPROVED** [review]
Looks good. Please resolve the merge conflict and I'll merge it.

**Pull request merged**
