### PR TITLE
Audio Manager Destroyed 

### PR DESCRIPTION
**Pull request by Markytt**
### Description
Fixed bug that occurred when you exited any mode and then entered match mode. This bug made it so that sound effects wouldn't play in match mode when the match started and error messages would appear saying that the audio manager has been destroyed. 

Julian wrote the code for this PR, I'm just uploading it to github for him. 

### Objectives
- [x] Fix the Audio Manager Destroyed bug 
- [x] Fix the 'Game Object Destroyed' Bug 

### Testing Done
- Entered match mode, started a match and then exited match mode multiple times to make sure that the sound effect would play and no error messages would appear
- Loaded in robots in match mode, exited to the main menu, and then re-entered match mode multiple times. 

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1565)

### CODE REVIEW

**Comment by a-crowell** [comment]
Can't play an ideal match after exiting/switching modes still, but AudioManager isn't one of those errors anymore good work!

Are we just fixing on the AudioManager destroyed error? There are enough bugs when it comes to switching modes and match mode for them to be done in one pr. I've started compiling them and can note them here or can put them on the backlog.

**Review by a-crowell — APPROVED** [review]
Don't get the AudioManager error anymore

**Review by a-crowell — COMMENTED** [review]
The Jira ticket linked can't be accessed, but is it this one? https://jira.autodesk.com/browse/AARD-1565?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel

If so, that isn't resolved
LeaveMiddleOfMatchReenter

**Comment by PepperLola** [comment]
> The Jira ticket linked can't be accessed, but is it this one? [jira.autodesk.com/browse/AARD-1565?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel](https://jira.autodesk.com/browse/AARD-1565?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel)
> 
> If so, that isn't resolved. The errors still come up after following steps to reproduce LeaveMiddleOfMatchReenter

I think that's a different one. The audio manager one should say something specifically about `AudioManager` in two of the error messages and how it's that component that it can't access.

**Review by LucaHaverty — APPROVED** [review]
Looks good, nice job!

**Review by Markytt — COMMENTED** [review]
I added code which should fix the 'Game Object Destroyed' bug. This steps to repeat this bug are to spawn in one or more robots in match mode, exited and re-enter match mode, then click load button, which would cause a bunch of error messages to appear. Please test my PR to make sure that this bug is gone now.

**Review by KyroVibe — APPROVED** [review]
Looks good. There is a weird bug where each match gets faster than the next, but I think that's a different bug that I'll catalog for now

**Pull request merged**
