### PR TITLE
AARD-1687: Save exporter options with active design

### PR DESCRIPTION
**Pull request by BrandonPacewic**
My overall conclusion? The exporter needs to be rewritten...

### Description

Small refactor to the parser options configurable from the settings panel. Now will save settings upon a robot export to the individual robot design.

### Objectives

- [x] Generalized exporter options class
- [x] Ability to save / load general options class
- [x] Refactor parser and config panel for new options class
- [x] Refactor parser and config panel to rely on enums

> [!note]
> Joint and specific wheel options are still not loaded properly (they do currently save), this will be a part of [AARD-1685](https://jira.autodesk.com/browse/AARD-1685)

> [!note]
> I also removed several of the exporter options that were not being used and that their removal did not immediately break anything.
> These options will likely be re-implemented and add back in the future.

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1687)

### CODE REVIEW

**Review by HunterBarclay — CHANGES_REQUESTED** [review]
It looks like the debug view is giving some interesting result. Joint type of 0 indicates essentially a disabled joint/no joint. Only really shows up when something isn't work (or at least it did). Furthermore, its showing non of the joints being wheels.

image

image

In addition, I can't find the Mirabuf file when trying to import it into Synthesis v6. It doesn't show up as an available robot.

And finally, it doesn't save which joints you actually want to export. Still automatically populates, but if I remove a joint and export, it reappears (not in debug view, meaning it didn't actually export). This will be moved so not really an issue.

**Comment by BrandonPacewic** [comment]
> It looks like the debug view is giving some interesting result. Joint type of 0 indicates essentially a disabled joint/no joint. Only really shows up when something isn't work (or at least it did). Furthermore, its showing non of the joints being wheels.

Fixed these issues.

> In addition, I can't find the Mirabuf file when trying to import it into Synthesis v6. It doesn't show up as an available robot.

It's possible that the `Export as Part` option was ticked, this would put it into the mix and match folder and not the normal robots folder.

> And finally, it doesn't save which joints you actually want to export. Still automatically populates, but if I remove a joint and export, it reappears (not in debug view, meaning it didn't actually export). This will be moved so not really an issue.

This will be added as a part of [AARD-1685](https://jira.autodesk.com/browse/AARD-1685).

**Review by HunterBarclay — CHANGES_REQUESTED** [review]
Bugs appear to be fixed. Whether an a wheel was labeled omni or standard wasn't save, but that can be done in the joint panel.

More pressing, however, is that Dozer won't spawn it. I can find it now (you were right, it was originally a part), but it appears that the grounded node or at least the body and face aren't being spawned into v6. Once I locate where the head of my `barclah/mira-upload` branch is, I'll add support for you to test dropping robots into v7 for testing since it'll provide you with much more detail.

image

**Comment by BrandonPacewic** [comment]
> [!warning]
> ~Current version of this branch creates an identical `.mira` file as the exporter currently on `dev`. The bug(s) that we are running into exist outside of these changes and should be fixed to validate that this branch is indeed working properly.~

**Comment by BrandonPacewic** [comment]
Well the problem was not with the exporter but with the importer in v6. Tryout the exported robot in `barclah/mira-upload` for testing.

~The robot will be found in `~/.config/Autodesk/Synthesis/Mira/`. We will update the exporter to show a panel to choose the export location in #980.~

**Review by HunterBarclay — COMMENTED** [review]
@BrandonPacewic Did some digging and it looks like if you selected a location previously, Fusion will override the default folder, which I'm fine with tbh. I added a ternary for the default `fileLocation` to check if the exporter is on Windows, and if so, get the `%HOME%` variable. @PepperLola Could you please verify on your end it still works on mac?

**Comment by HunterBarclay** [comment]
@LucaHaverty When you have Fusion installed, follow the `/exporter/SynthesisFusionAddin/README.md` for setup, and see if you can export Dozer, checking to see if the file dialog initially takes you to the user directory. Please let me know if you need help setting up, as well as your email so I can add you to the Fusion hub.

**Comment by HunterBarclay** [comment]
@BrandonPacewic Are we going to let the Black formatter fail for this PR? I saw you working on it earlier today.

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic Are we going to let the Black formatter fail for this PR? I saw you working on it earlier today.

@HunterBarclay 

Yes we can let it fail, updates are ready to go once we get everything merged in from current open PRs.

**Review by HunterBarclay — APPROVED** [review]
Looking and working great on MacOS. @BrandonPacewic Could you pull this down to your work laptop and verify that the windows home folder in the FileDialog works?

**Comment by BrandonPacewic** [comment]
@HunterBarclay 

> Looking and working great on MacOS. @BrandonPacewic Could you pull this down to your work laptop and verify that the windows home folder in the FileDialog works?

:+1: Everything works on both windows and mac for me.

**Comment by HunterBarclay** [comment]
@BrandonPacewic Pulling it down on my Windows machine rn. Once I get Fusion updated on my Windows machine, I'll test and bypass the 2 review restriction

**Comment by HunterBarclay** [comment]
@BrandonPacewic Added fix for Windows deps installation. Clearing issues on security bandit due to a false positive. Still haven't tested the home folder directory due to it navigating to the last used directory. I'm asking in API slack channel to see if there is a work around for testing.

**Pull request merged**
