### PR TITLE
Fixed modal/panel tween issue

### PR DESCRIPTION
**Pull request by LucaHaverty**
### Description
Fixed issues around modal and panel tweening, specifically when open or close function were called while a tween is running.

### Testing Done
- Double clicking accept when spawning a robot
- Opening a modal before another one finishes opening

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1609)

### CODE REVIEW

**Review by Markytt — CHANGES_REQUESTED** [review]
When you exit a mode and then enter either the same mode again, or a different mode, nothing will show up besides an error message. 

Screenshot 2023-08-15 161808

**Review by a-crowell — APPROVED** [review]
Not fast enough to test opening another modal while one is being created, but spawning multiple robots looks good!

**Review by Markytt — APPROVED** [review]
Looks good

**Review by BrandonPacewic — APPROVED** [review]
Makes me happy to see those manual formatting changes.

**Pull request merged**
