### PR TITLE
Network integration

### PR DESCRIPTION
**Pull request by MackinnonBuck**
Finished integrating network multiplayer with the new UI.

Testing should involve making sure that everything still functions in the normal simulator. Network multiplayer mode itself is also ready to be started testing.

### CODE REVIEW

**Comment by MackinnonBuck** [comment]
Merge conflicts have been resolved.

**Comment by HiceS** [comment]
@BradenMccoy can you test this before testing anything else to make sure we are on track for the release.

**Comment by MackinnonBuck** [comment]
That should be fixed now. It's a Unity bug that sometimes adds GameObject components to the prefabs themselves. We'll just have to make sure the NetworkElement prefab doesn't have any NetworkMesh components attached to it when we do the final build.

**Comment by HiceS** [comment]
@BradenMccoy

**Comment by BradenMccoy** [comment]
Multiplayer is currently LAN-only, the possibility of global multiplayer is being investigated.

**Comment by BradenMccoy** [comment]
@HiceS Through testing we discovered that network multiplayer does not work (except for LAN), @MackinnonBuck is currently looking into something that would allow for global multiplayer.

**Comment by MackinnonBuck** [comment]
Just fixed some merge conflicts, now doing some final testing to make sure nothing broke. Then I'll merge the PR.

**Pull request merged**
