### PR TITLE
Joint Editor Window UI

### PR DESCRIPTION
**Pull request by KiraCorbett**
This is the base UI for joint configuration in the engine. 

This PR does include:
:heavy_check_mark: Joint Editor UI with functionality from @copernicium per #633 
:heavy_check_mark: "Highlighting" a current joint when the highlight button is selected. Added highlighting improvements per #632 
:heavy_check_mark: Custom dropdowns from @rasberrypai per #642 
:heavy_check_mark: Organization of joints per entity #635 

image

### CODE REVIEW

**Comment by KiraCorbett** [comment]
Pending on some feedback for this API error. After an update from master and updating the dll many times, I am still not able to correct this.
image

**Comment by copernicium** [comment]
> Scrolling or moving the window with dropdowns open causes the dropdown to disconnect from the window and remain open.

@rasberrypai Would you be able to work on fixing this bug?

**Comment by matthew17754** [comment]
Any particular reason why right-clicking force-closes the form?

**Comment by KiraCorbett** [comment]
> Any particular reason why right-clicking force-closes the form?

The right-click deselects the entity so that will naturally close the windows associated with that entity.

**Comment by matthew17754** [comment]
Hitting the red **X** throws `Joint broken, cannot set`. Not sure if this is related to the Joint Editor but it is critical all the same.

**Comment by copernicium** [comment]
> Hitting the red **X** throws `Joint broken, cannot set`. Not sure if this is related to the Joint Editor but it is critical all the same.

This is an issue with the Joint implementation. I think it should be fixed as a part of a separate PR, one that refactors how we handle joints.

**Review by matthew17754 — APPROVED** [review]

**Pull request merged**
