### PR TITLE
Haverty/elevator bug

### PR DESCRIPTION
**Pull request by LucaHaverty**
### Description
Fixed strange elevator behavior by adding velocity control. Elevator stages can now be controlled independently with much greater accuracy. Also reduces elevator stages moving each other and arms bouncing when reaching a position limit.

### CODE REVIEW

**Review by HunterBarclay — COMMENTED** [review]
Looks good. We'll wait for #977

**Review by a-crowell — COMMENTED** [review]
Waiting on review? The last commit was my approval for both input manager and this so probably good to go, just merge first.

**Review by HunterBarclay — CHANGES_REQUESTED** [review]
It seems to move pretty well. The major thing for me is how much the elevator pieces get tossed around. When moving the carriage, it shifts the second stage of the elevator a ton. Same with the arm movement. Is there something we can do to essentially add movement braking?

**Review by HunterBarclay — APPROVED** [review]
Perfect. Great work

**Review by a-crowell — APPROVED** [review]
Woah this is so much better! All from weakening it a bit. Nice work.

**Comment by HunterBarclay** [comment]
@LucaHaverty Could you resolve the merge conflicts, then we can merge this in

**Pull request merged**
