### PR TITLE
Auto Updater GUI

### PR DESCRIPTION
**Pull request by khuntetad**
Completed a functional update button that spawns anytime the user's Synthesis is a lower version than the highest version available. In order to complete this task, we created a AutoUpdater script accompanied by a panel with buttons that allow the user to either update or complete the update later. In addition, the version of Synthesis that the user is currently using is displayed in the top right corner.

Screenshot (10)

AARD-1348
[Auto Updater GUI](https://jira.autodesk.com/browse/AARD-1348)

### CODE REVIEW

**Review by matthew17754 — CHANGES_REQUESTED** [review]
Move the version number onto the toolbar in-line with the Settings and About icons.

**Comment by HiceS** [comment]
Make that title text quite a bit smaller. There should be a healthy margin on the top and bottom of the header.

**Comment by KyroVibe** [comment]
image
image
Changed some of the UI

**Review by KyroVibe — APPROVED** [review]
Looks good. Implemented the last little changes I wanted already. @khuntetad and @matthew17754 Approve the new look?

**Comment by khuntetad** [comment]
> Looks good. Implemented the last little changes I wanted already. @khuntetad and @matthew17754 Approve the new look?

Yeah looks good

**Review by matthew17754 — APPROVED** [review]
Looks good

**Pull request merged**
