### PR TITLE
Friction Data Export

### PR DESCRIPTION
**Pull request by azaleacolburn**
### Description
Serializes the friction override for the wheels of a robot if the checkbox is clicked. Additionally this PR creates a friction lookup table for when friction isn't overrided.

The friction override is for the `dynamic_friction` and `static_friction` fields in the each [ProtoMaterial](https://www.mirabuf.dev/#mirabuf.material.PhysicalMaterial) in the exported mirabuf.

### Todo:
- [x] Export Friction Override
- [x] ~~Parse Friction Override in fission~~ (Beyond the scope of the PR)

### Testing Done
- [x] Friction correctly set in exporterOptions
- [x] ~~Friction correctly serialized and deserialized (Not sure exactly how to test this without fission allowing a friction override in fission)~~ (See above)

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1723)

### CODE REVIEW

**Comment by BrandonPacewic** [comment]
@HunterBarclay Do we still want to do Fission integration as a part of this PR? If so we should mark this as draft and leave it for after the MVP.

**Review by BrandonPacewic — COMMENTED** [review]
@HunterBarclay Do we still want to do Fission integration as a part of this PR? If so we should mark this as draft and leave it for after the MVP.

**Review by BrandonPacewic — COMMENTED** [review]
- ~~There appears to be aps auth stuff in here, perhaps a conflict with #1004?~~

**Comment by PepperLola** [comment]
I got this error when I set an override:
```
Synthesis.Material.getPhysicalMaterialData - ERROR - Failed:
  File ".../synthesis/exporter/SynthesisFusionAddin/src/Parser/SynthesisParser/Materials.py", line 99, in getPhysicalMaterialData
    physical_material.dynamic_friction = dynamic_friction_coeffs.get(fusion_material.name, 0.5)
    ^^^^^^^^^^^^^^^^^
NameError: name 'physical_material' is not defined
```

Also, are there supposed to be two buttons?
Screenshot 2024-07-24 at 3 29 20 PM

**Review by BrandonPacewic — APPROVED** [review]
LGTM!

Let's get this in ASAP so I can finish #1032 🙃

**Review by PepperLola — APPROVED** [review]
Looks good

**Pull request merged**
