### PR TITLE
New User Interface Design for Toolbars

### PR DESCRIPTION
**Pull request by victorxheng**
Completely redid the navigation bar, rewriting the previous Bar script into one single NavigationBar script that manages tabs and panels with the LayoutManager. 

The new nav-bar is saved as a prefab that can be dragged in in case of merge conflicts in the scene. The tab switching uses instantiation and destroying tabs onto the tab transform.

image

### CODE REVIEW

**Review by KyroVibe — CHANGES_REQUESTED** [review]
Everything is great, except you forgot to change the style of the dropdown in the game pieces tab

**Comment by victorxheng** [comment]
Made the Dropdown look like the figma

**Review by KyroVibe — APPROVED** [review]
Looks great, we'll update the drop down again when the mock ups get updated

**Review by khuntetad — APPROVED** [review]
Looks good

**Pull request merged**
