### PR TITLE
Removed unused settings

### PR DESCRIPTION
**Pull request by NWalker1208**
Removed settings from the settings menu that the user no longer needs:
- Robot directory (will always be AppData)
- Fancy colors (set in the save menu)

This resolves AARD-546.

### CODE REVIEW

**Comment by NWalker1208** [comment]
Will return with more commits to remove other items from toolbar.

**Comment by NWalker1208** [comment]
Removed other toolbar items to resolve AARD-555 as well.

**Comment by MackinnonBuck** [comment]
@NWalker1208 Could you resolve the merge conflicts so the merging can proceed?

**Comment by HiceS** [comment]
@NWalker1208 take the diff.

**Pull request merged**
