### PR TITLE
Re-Added DLL

### PR DESCRIPTION
**Pull request by victoryforphil**
## Table

|    DOD    | Done |    Reviewer    | Issue | Notes |
|-----------|------|----------------|-------|-------|
| Code      | ❌    | Matthew Moradi / Shawn Hice |   663|       |
| Unit Test | N/A  | N/A            |       |       |
| Merged    | ❌    |                |       |       |

### CODE REVIEW

**Comment by victoryforphil** [comment]
Its the DLL issue again. For some reason, it won't keep track of the DLL. Once you add Simulation DLL it works.

**Comment by victoryforphil** [comment]
Lots of things got broken with git. Spending time to redo this commit.

**Comment by victoryforphil** [comment]
@matthew17754 Try it now? I merged from master and it seems clean. If there are issues let me know.

**Comment by KiraCorbett** [comment]
It would be good to build in Unity before merging with master since the DLL files also effect Unity.

**Comment by matthew17754** [comment]
Please submit a new PR from a fresh branch off of master with your changes.

**Pull request closed without merging**
