### PR TITLE
Practice Match

### PR DESCRIPTION
**Pull request by MrRoboman4321**
A stopwatch-esque feature, but emulates the timer used in FRC matches. Main GameObject elements are PracticeMatchPanel and ConfirmationPanel, and the main script is PracticeMatch.cs.

### CODE REVIEW

**Comment by MrRoboman4321** [comment]
If any clarification needs to be made, please just ask and I'll fill in the other details. I wasn't fully sure what you wanted in documentation on the pull request.

**Comment by tRidha** [comment]
Thanks for the submission! We'll fully review and judge the pull request along with the rest after the Code Sprint deadline has passed (August 20th). 

All looks good with your submission with the changes, description, and documentation. However, we just need your name and team number so that we know who to link this to. In addition to that, could you please fill out [this submission form](https://docs.google.com/forms/d/1ctaDty_jgkmwNIBfBCgNr_OD9gdnGqcfHEznOWuWre4/viewform?edit_requested=true)?

Thank you,
Thariq Ridha

**Comment by MrRoboman4321** [comment]
I filled out the form once already, do I need to again?

**Comment by tRidha** [comment]
Oh sorry, there was a bit of internal miscommunication here and I was told that you haven't filled it out. We just checked and we have your form submission. Sorry about the confusion!

**Comment by tRidha** [comment]
Thanks for the submission! We'll review all the submissions over this week and the next and let you know the results of the Code Sprint soon.

Thariq

**Pull request closed without merging**
