### PR TITLE
Rename FusionExporter to FusionRobotExporter

### PR DESCRIPTION
**Pull request by nicolasespinoza**
### Rename FusionExporter to FusionRobotExporter
As we prepare to release the new Fusion 360 plugin to FRC teams and users, we should create a bit more uniformity and clarity in the naming of our projects. This would also make it less confusing for outside contributors.

- Updated all FusionExporter references to FusionRobotExporter
- Updated all FusionSynth references to FusionRobotExporter
- Updated all FusionSynthV2 references to FusionRobotExporter

### Jira
- Issue 1101

|    DOD    | Done |    Reviewer    | Issue | Notes |
|-----------|------|----------------|-------|-------|
| Code      | ❌   | Mat Moradi / Liam Wang / Kira Corbett |  1101 |       |
| Unit Test | N/A  | N/A            |       |       |
| Merged    | ❌  |                |       |       |

**This will also merge #377.**

### CODE REVIEW

**Comment by matthew17754** [comment]
Personally I'd rather just rename the **BxDRobotEporer** to **InventorExporter**, but I'd like to hear some other feedback.

**Comment by nicolasespinoza** [comment]
> Personally I'd rather just rename the **BxDRobotExporter** to **InventorExporter**, but I'd like to hear some other feedback.

But wouldn't `Exporter` become a little too broad since we have a Field Exporter(s)?

**Comment by matthew17754** [comment]
True, but there's only one Field Exporter, and it's Standalone and only for internal use.

**Comment by nicolasespinoza** [comment]
> Personally I'd rather just rename the **BxDRobotExporter** to **InventorExporter**, but I'd like to hear some other feedback.
> True, but there's only one Field Exporter, and it's Standalone and only for internal use.

I like your idea. If Shawn agrees I'll close this and we can do that instead.

**Comment by wangl5** [comment]
@nicolasespinoza Also, the project name should be updated in the READMEs in the `exporter` and `exporter/FusionSynth` folders and in the wiki if you haven't done that already.

**Comment by nicolasespinoza** [comment]
@matthew17754 We should be good now. The wikis have also been updated

**Pull request merged**
