### PR TITLE
Export wizard wheels

### PR DESCRIPTION
**Pull request by JoshGrace**
removed the basic robot setup page
moved drive train selection and mass to wheel setup
made wheel setup drag and drop based

### CODE REVIEW

**Comment by HiceS** [comment]
Alright ill close the request, @NWalker1208 can either make the changes or @JoshGrace can depending on what @kirac2093 thinks.

**Comment by JoshGrace** [comment]
I've fixed the typo issues and the PWM ports not being filled correctly. Also, I've fixed an issue with the PWM values being set with a minimum of 1 instead of 0.

**Comment by JoshGrace** [comment]
@BradenMccoy @NWalker1208  can one of you check this on Monday?

**Comment by LaurenChoquer** [comment]
I can read over it on Monday as well.

-Lauren

**Comment by NWalker1208** [comment]
The exception I pointed out still exists. Also, instead of adding try-catch structures everywhere, try to find the source of the problem. I suspect that you need to check if the selected item is null, and then stop attempting to drag the item if it equals null.

**Comment by HiceS** [comment]
@BradenMccoy build and test his changes, if you encounter a exception then let josh know.

**Comment by HiceS** [comment]
about time

**Pull request merged**
