### PR TITLE
Fixed scrollbar

### PR DESCRIPTION
**Pull request by LucaHaverty**
### Description
Replaced the chunky default scrollbar with a much cleaner one

### Before
Screenshot 2024-08-06 164404

### After
Screenshot 2024-08-06 164243

### CODE REVIEW

**Review by Dhruv-0-Arora — APPROVED** [review]
Screenshot 2024-08-06 at 6 14 39 PM

Looks good

**Review by a-crowell — APPROVED** [review]
Beautiful

**Comment by HunterBarclay** [comment]
@azaleacolburn Is there a way to clear the playwright cache? Looks like the version is out of date or something.

**Review by BrandonPacewic — COMMENTED** [review]
Is this the PR that fixes [AARD-1801](https://jira.autodesk.com/browse/AARD-1801)? Or was that in something else?

**Comment by LucaHaverty** [comment]
> Is this the PR that fixes [AARD-1801](https://jira.autodesk.com/browse/AARD-1801)? Or was that in something else?

@BrandonPacewic That's something else. I could probably throw it in this pr though

**Comment by HunterBarclay** [comment]
@LucaHaverty Are we merging this PR now or waiting for 1801?

**Comment by LucaHaverty** [comment]
> @LucaHaverty Are we merging this PR now or waiting for 1801?

@HunterBarclay merge now

**Pull request merged**
