### PR TITLE
Fix Synthesis opening regardless of "Open Synthesis" checkbox at export

### PR DESCRIPTION
**Pull request by nicolasespinoza**
### Fix Synthesis opening regardless of "Open Synthesis" checkbox at export

https://github.com/Autodesk/synthesis/blob/256e9d45becb12b8c741da3fd3278c8ecca62502/exporters/InventorRobotExporter/InventorRobotExporter/Utilities/Synthesis/SynthesisUtils.cs#L15-L18

### Jira
- Issue 1139

|    DOD    | Done |    Reviewer    | Issue | Notes |
|-----------|------|----------------|-------|-------|
| Code      | ❌   | Liam Wang / Alex Carter / Kira Corbett |  1139 |       |
| Unit Test | N/A  | N/A            |       |       |
| Merged    | ❌  |                |       |       |

**This will merge #394**

### CODE REVIEW

**Comment by wangl5** [comment]
@matthew17754 Fixed

WideFinish

**Comment by wangl5** [comment]
@matthew17754 Good idea, I increased the font size.

I think that even if synthesis is opening, the user should know that the export was successful and the location of the output directory. Are you sure it isn't necessary?

**Comment by nicolasespinoza** [comment]
> @matthew17754 Good idea, I increased the font size.
> 
> I think that even if synthesis is opening, the user should know that the export was successful and the location of the output directory. Are you sure it isn't necessary?

I think the reason he suggested it is because when you open Synthesis it covers the entire screen, so the user wouldn't even notice the dialog.

**Comment by wangl5** [comment]
@nicolasespinoza Okay, now it will always display on top

**Pull request merged**
