### PR TITLE
Export refactor

### PR DESCRIPTION
**Pull request by NickBurrell**
DO NOT MERGE. NOT READY.

Submitting PR early. Needs further testing by other developers. Currently encountering Fusion issues when debugging.
Some pending changes still in progress, namely:
 - Reintegrating Analytics
 - Updating to non-relative import paths
 - Complete refactor to comply with PEP8 standards
 - Move UI Callbacks back to ui_callbacks.py 
     - This was done for testing purposes. Ideally, no file has more than 500 lines in it. Currently config_command.py has ~1500 without callback refactor
  - Finish refactor of globals/callback

### CODE REVIEW

**Comment by HiceS** [comment]
Okay so one of the key agreements in the very start of the internship was there will be no work done on the exporter as it's the only relatively finished product in the repository and refactoring will not in any way contribute to finishing the deadlines.

However adding new features that are necessary or fixing bugs is important.

I would advise you find a more relevant task and archive this branch unless it contains any useful additions to helping you meet your deadline.

Thank you for showing progress, I wish you would have done this sooner.

**Review by HiceS — CHANGES_REQUESTED** [review]
Only relative imports worked as part of the debugging process and on both windows and osx, the style guidelines for formatting are defined by black. Verify this works on both machines before approval.

**Comment by KyroVibe** [comment]
> Okay so one of the key agreements in the very start of the internship was there will be no work done on the exporter as it's the only relatively finished product in the repository and refactoring will not in any way contribute to finishing the deadlines.
> 
> However adding new features that are necessary or fixing bugs is important.
> 
> I would advise you find a more relevant task and archive this branch unless it contains any useful additions to helping you meet your deadline.
> 
> Thank you for showing progress, I wish you would have done this sooner.
> 

We met with Pam and agreed that a refactor was necessary. The UI is in shambles and is the biggest bottleneck when introducing new features into the exporter. This is also a prerequisite to caching the configuration so the user is t required to repeat setup when they change something small. While we said at the beginning that we were going to avoid major changes to the exporter, we decided that it was worth moving Nick over to work on this

**Comment by HiceS** [comment]
I’ll have a chat with Pam on why this was allowed and see if we need to update everyone on the goals for the summer. Seems like there is conflicting information on what the end goal is yet again. 

For the record caching was always a thing. I asked yazen to specifically remove it to not trigger a file change every export. 

Unless there is a feature change it would set a bad precedent to merge this as it doesn’t resemble teamwork.

**Comment by KyroVibe** [comment]
> 

We were specifically asked by Pam to add in caching as she made a point that it was a user pain point and we agreed. While the refactor wasn't completely vital, we agreed, with Pam, that it was necessary to move forward with working on the exporter. This was not some free-time side project, it was a team-ordered decision that we asked him to do. He isn't even an exporter developer, we specifically moved him to the exporter to tackle this task.

Addressing this user pain point, and the work put it leading up to it, was something that we determined to be an appropriate use of time. If we had something more critical than this that would have benefited from Nicks's time, we would've put him on that.

**Comment by HiceS** [comment]
If the refactor isn’t vital it is by definition tech debt. 

We aren’t addressing tech debt currently because there is no deliverable. 

Sorry I typed out a whole thing but I realized I’m just having a bad day and this is not at all what I wanted to see as progress. I’ll chat with Pam to double check she understands what this change means and then we can agree whether or not this is valid work.

**Comment by HiceS** [comment]
If Nick wants to implement something on the exporter and contribute code. I’ll approve a PR with saving. Or with 1 click export. Or with a better module resolution system. Or fixing some of the edge cases with the exporting. 

The fact is with the time and changes made in this PR he could have done all of those.

**Pull request closed without merging**
