### PR TITLE
Merge `fusion-devel` into master

### PR DESCRIPTION
**Pull request by wangl5**
### Merge `fusion-devel` into master

- Currently, no analytics have been added `(AARD-1056)`
- The following are included in the UI but are **not** written to the JSON file `(AARD-1163)`
    - Per-joint weight
    - Drivetrain weight
    - Gearing

### CODE REVIEW

**Comment by matthew17754** [comment]
Please resolve the merge conflicts

**Comment by HiceS** [comment]
jsonbug

Steps to reproduce:
1. Open Fusion 360
2. Open Robot Model
3. Go to Synthesis Workspace
3. Select Drive Train Type
[CRASH]

**Comment by wangl5** [comment]
JSON parsing should be fixed now. (why, https://github.com/Autodesk/synthesis/pull/419)

**Comment by zero-frost** [comment]
There were changes (mostly reversions from what I can tell) to emulation files. Before we merge this in, those need to be resolved. The version on Master is the correct ones and should be the ones we end up with.

**Pull request merged**
