### PR TITLE
 Rename drive train type to drive train layout and rename options

### PR DESCRIPTION
**Pull request by wangl5**
### Rename drive train type to drive train layout and rename options
- Merge #376

DTrename

|    DOD    | Done |    Reviewer    | Issue | Notes |
|-----------|------|----------------|-------|-------|
| Code      | ❌   | Nicolas Espinoza/Alex Carter|  1128|       |
| Unit Test | N/A  | N/A            |       |       |
| Merged    | ❌  |                |       |       |

### CODE REVIEW

**Comment by nicolasespinoza** [comment]
It works, but I think "Standard" is too broad.

@KiraCorbett What are your thoughts?

**Comment by KiraCorbett** [comment]
I have pulled a few times and re-opened the InventorRobotExporter project but am still not able to see the change. @nicolasespinoza I posted a message on the non-dev Slack channel to get feedback about the terminology. Maybe "Basic" would be a more simplified word? image

**Comment by nicolasespinoza** [comment]
> I have pulled a few times and re-opened the InventorRobotExporter project but am still not able to see the change (probably a local issue.) @nicolasespinoza I posted a message on the non-dev Slack channel to get feedback about the terminology. Maybe "Basic" would be a more simplified word? image

It's because of the project rename. All you have to do is close Inventor and then delete `ApplicationPlugins` in `C:\Users\t_corbk\AppData\Roaming\Autodesk`

**Comment by wangl5** [comment]
Sounds good, I changed it to `Basic` as we decided that would be a better label.

**Comment by matthew17754** [comment]
Please resolve the merge conflicts

**Comment by matthew17754** [comment]
For such a small change, I'd recommend a new PR or a squash @wangl5

**Comment by wangl5** [comment]
@matthew17754 Whoops, good catch! This branch originally had more changes but for some reason, #395 was merged before this branch so the changes were merged without being reviewed. The change should be back now.

**Pull request merged**
