### PR TITLE
Code Cleanup: Unused code

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Component of #838.

### Description
Lots of old commented out code in this project. Makes everything feel cleaner and more professional if we keep things nice and clean. 

Note: This will be the last pr merged this sprint to avoid conflicts. 

### Objectives
- [x] Remove commented out code.
- [x] Remove leftover `Debug.Log`s.
- [x] Fix any `clang-format` discrepancies. 

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1549)

### CODE REVIEW

**Comment by KyroVibe** [comment]
Whats the difference from #838 ?

**Comment by BrandonPacewic** [comment]
> Whats the difference from #838 ?

There is some small elements that are different, mainly what got removed. This pr also does not contain some changes that #838 has. For example #838 adds brackets to all `if`s and `for`s.

**Comment by BrandonPacewic** [comment]
@KyroVibe Since there are no syntax errors I'm going to assume that everything is working fine.

**Comment by KyroVibe** [comment]
> @KyroVibe Since there are no syntax errors I'm going to assume that everything is working fine.

Fair assumption

**Comment by KyroVibe** [comment]
@BrandonPacewic I'm going to just run the Engine CI on this branch, and if it passes, I'll bypass the reviews

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic I'm going to just run the Engine CI on this branch, and if it passes, I'll bypass the reviews

Sounds good, if it ends up breaking something just let me know and I'll fix it.

**Pull request merged**
