### PR TITLE
Simple card layout joint editor

### PR DESCRIPTION
**Pull request by wangl5**
#### Remove the following options:
- Motor type
- Brake
- Friction level
- Joint limits (can be set up using the Inventor joint limit editor)

#### Moved the following less frequently used options into an advanced editor
- Gear ratio (default: 1)
- Sensors
- PWM/CAN port (default: CAN 3)

SimpleJointEditor

|    DOD    | Done |    Reviewer    | Issue | Notes |
|-----------|------|----------------|-------|-------|
| Code      | ❌   | Nicolas Espinoza/Alex Carter|  1140|       |
| Unit Test | N/A  | N/A            |       |       |
| Merged    | ❌  |                |       |       |

### CODE REVIEW

**Comment by wangl5** [comment]
@nicolasespinoza Good catch! That issue should be fixed now.

**Comment by nicolasespinoza** [comment]
A few more things:
1. There seems to be a weird container extension when you select "Mechanism Joint":

Demo

2. Whenever I click "OK" in the Joint Editor, my screen flashes white for maybe a quarter of a second?

Besides that, it seems to export fine.

**Comment by wangl5** [comment]
@nicolasespinoza Thanks, fixed the table width, I'm not sure what the white screen flashing is though

**Comment by wangl5** [comment]
@matthew17754 
Should be fixed now, the main joint editor window needed to always display on top so users could interact with the inventor window without hiding the joint editor.

**Comment by wangl5** [comment]
@matthew17754 Okay, the width is decreased, let me know if it looks good on your display now.

**Pull request merged**
