### PR TITLE
Create pre-check window in Inventor robot exporter

### PR DESCRIPTION
**Pull request by wangl5**
### Create pre-check window in Inventor robot exporter
- HTML guide of steps for exporting a robot
- Some steps have links to existing synthesis tutorials on youtube
- "Robot Export Guide" button in the ribbon toggles the pre-check visibility
- HTML is formatted to look similar to the "Simulation Guide" in the Inventor static stress analysis environment

Capture2

### Jira
- Issue 996

|    DOD    | Done |    Reviewer    | Issue | Notes |
|-----------|------|----------------|-------|-------|
| Code      | ❌   | Alexander Carter |   996 |       |
| Unit Test | N/A  | N/A            |       |       |
| Merged    | ❌  |                |       |       |

### CODE REVIEW

**Comment by wangl5** [comment]
Also, any edits to make the guide clearer are welcome.

**Comment by KiraCorbett** [comment]
Hold off on merging. Adding a few people to look over the current content in the guide then will approve and merge until we hear from users to update the guide (if applicable.)

**Comment by victoryforphil** [comment]
For right now this looks good, but I feel the original intent behind this was to do an automatic checklist. That shows errors. But for right now this will do.

**Comment by wangl5** [comment]
@victoryforphil Yeah, I should have explained that I was thinking

**Comment by wangl5** [comment]
SimulationGuide

**Pull request merged**
