### PR TITLE
Sticky Hatches

### PR DESCRIPTION
**Pull request by KyroVibe**
You can label a goal as "Sticky" and it will make the gamepiece stick to the goal. Please test this with your own setup to see if it is compatible with existing field goals.
(I couldn't find the JIRA issue I thought existed)

### CODE REVIEW

**Comment by KyroVibe** [comment]
@matthew17754

**Comment by KiraCorbett** [comment]
The sticky addition is pretty neat! I was actually able to get a robot to lift a few inches off the ground through a chain effect by sticking the gamepiece on the object -> then picking up the gamepiece from the sticky point which caused the robot to "climb." 

A few things to double check:
- When a gamepiece is stuck to a different object, it doesn't seem to increment the scoreboard. 
- Do you have a consistent way of getting a gamepiece to stick? It seemed to work well in the 2019 field with a ball but I couldn't get a hatch panel to stick. If you have a few steps you recommend, let me know so I could re-test. The smaller gamepieces were kind of hard to deal with. 

For now, let's double check the scoreboard and since the sticky feature is an improvement we can probably merge it and add the task to improve smaller pieces (like the hatch later.)

**Comment by KiraCorbett** [comment]
@KyroVibe I forgot to add this image. When I created a giant goal, where does the sticky action take place? On the edge of the defined goal? 
image

**Comment by KyroVibe** [comment]
@KiraCorbett Yes, the goals are supposed to match the shape and position of the hook and loop tape so where ever the gamepiece hits, that is where it should stick to.

**Comment by KiraCorbett** [comment]
Messaged @KyroVibe and we are thinking of doing more testing to make sure we get consistent results before merging into master.

**Comment by KyroVibe** [comment]
@KiraCorbett I added a little warning message that will popup. Basically it will display whenever the sticky feature is enabled and then will go away semi-permanently when you click the "I Understand" button. It will, however, reset after you restart synthesis. If you would like it to go away permanently, I can change it.

**Pull request merged**
