### PR TITLE
Settings Panel and UI

### PR DESCRIPTION
**Pull request by victorxheng**
Settings Panel is a prefab called from a nav-bar button. The panel can spawn different settings and read their states. The script that does this is on the panel. However, it is not integrated with the preference manager and input manager, thus, all that is there are tests.

image

[1280 Settings and UI](https://jira.autodesk.com/browse/AARD-1280)

### CODE REVIEW

**Comment by victorxheng** [comment]
Accidentally pushed commits from 1323 translate panels to this PR. 

1323: For spawning robots and fields, legacy type robots and fields are first saved as a translated file in the same directory before being imported. When the panel is next opened, the new translated file appears, allowing someone to spawn in objects directly without translation. Currently, these objects appear at the top in a group with the file name (type of "spr" included in the tag). 

The other commit changed the file name of UIManager to PanelManager because it was interfering with the Synthesis API UIManager in the Toastlogger class.

image

In the image above, the top two options are the already translated robot files. The importer differentiates the two by detecting if it is a file or a directory.

image

Spawning dozers have never been more efficient!

JIRA Tasks:
[1323](https://jira.autodesk.com/browse/AARD-1323)
[1280](https://jira.autodesk.com/browse/AARD-1280)

**Review by KyroVibe — CHANGES_REQUESTED** [review]
It looks like something happened during one of your merges because there is a GameObject in the root of the Hierarchy that looks out of place. Also the button for settings got disconnected from the panel it was supposed to spawn. Also instead of having it be some controller icon on the home tab, there is a gear icon on the top right that is for settings. The Translating looks all good

**Comment by victorxheng** [comment]
Fixed the out-of-place label in the hierarchy due to merge conflicts. Fixed the buttons, saved home tab as prefab, and linked the settings gear icon as the one for the settings panel.

**Review by NickBurrell — APPROVED** [review]
Builds and runs as expected, LGTM. Approved

**Review by khuntetad — APPROVED** [review]

**Review by matthew17754 — APPROVED** [review]

**Review by KyroVibe — APPROVED** [review]
Looks good, nice job

**Pull request merged**
