### PR TITLE
Fixed tab highlighting and added custom impulses panel

### PR DESCRIPTION
**Pull request by KyroVibe**
I made all the tabs properly highlight and also added a panel to apply custom impulses to the robot to test its ability to recover from impacts
JIRA issues:
https://jira.autodesk.com/browse/AARD-1080
https://jira.autodesk.com/browse/AARD-916

### CODE REVIEW

**Comment by KyroVibe** [comment]
@KiraCorbett all the panels do that its just that the point impulse panel is set to render of the loading panel. Fortunately its a very simple fix

**Comment by KyroVibe** [comment]
Sometimes the cursor is there sometimes it isn't. It is a bug inside of unity that we can't fix.

**Comment by matthew17754** [comment]
Perhaps make the text disappear?

**Comment by KyroVibe** [comment]
Again, that's handled unity side

**Comment by KyroVibe** [comment]
I limited the max value to 6 characters. Anything 4 or above isn't even useful.

**Pull request merged**
