### PR TITLE
Modal and Panel Rework

### PR DESCRIPTION
**Pull request by LucaHaverty**
### Description
A rework of all of the Panels and Modals based on the [example UI](https://www.figma.com/file/12FH7EqF8TRqgvONEwvHTp/2023-MainMenu?type=design&node-id=0-1&mode=design&t=4BYL7b6jsAfNWOcf-0). A big part of this pr is reworking most of the individual components. Here is a list of most of those changes:

Buttons - color, size, font size, color and scale hover effects

Screenshot 2023-07-20 100351

Radio select - same as the old toggle. Used when selecting mutually exclusive options

Screenshot 2023-07-20 102320

Slider - Color, label rounding when wanted (theme editor)

Screenshot 2023-07-21 163226

Toggle - Now is a square with a checkmark to distinguish from the radio select buttons

Screenshot 2023-07-21 163151

Dropdown - color, spacing, hover color and scale effects, checkmark

Screenshot 2023-07-20 102219

Each panel and modal has been upgraded with these new UI elements and the spacing has been adjusted. Additionally, modals and panels now have open and close animations using the new tween library. 

Another important change to note is that some elements now use nested prefabs. For example, the labeled dropdown now contains a dropdown prefab so changes to the dropdown prefab will affect both.

### Objectives
- [x] Update all UI elements (slider, button, etc.)
- [x] Modal header and footer spacing
- [x] Panel header and footer spacing
- [x] Individually finalize the spacing of all modals and panels
- [x] Make sure every modal and panel has an icon
- [x] Animate panels and modals opening/closing with the new tween library
- [x] Fix color animations of gradients on button and dropdown

### Testing Done
- Tested functionality of all modals and panels
- Tested individual ui elements
- Made sure the open/close tween animations didn't mess up persistent panels and modal callbacks

**Reviewers: make sure to switch back to the default theme to get all of the color changes**

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1570)

### CODE REVIEW

**Review by KyroVibe — CHANGES_REQUESTED** [review]
I'd like it if you made the panel/modal scaling tween a little snappier. Try using a cubic ease in for closing and a cubic ease out for opening.

I noticed that the toggles initially show their checkmark regardless of their state, then after clicking them it will update properly.
image

There are also a bunch of "ToasterComp" gameobjects that seem to be the result of some weird scene file merging. These, I'm pretty sure, are only supposed to be created and destroyed at runtime so idk what happened there.
image

**Review by a-crowell — CHANGES_REQUESTED** [review]
Looks great! The only thing is that session button text is in white instead of black for panels.

image

**Comment by a-crowell** [comment]
Is this new? The error shows up upon spawning a robot then clicking Multibot.
image

**Review by a-crowell — APPROVED** [review]
Nice job

**Review by Markytt — CHANGES_REQUESTED** [review]
Clicking cancel when you try to spawn a score zone will cause error messages to appear. 
Screenshot 2023-07-25 154557

**Review by Markytt — APPROVED** [review]
Everything is working good now.

**Review by KyroVibe — CHANGES_REQUESTED** [review]
Could you make the accordion button and the close button on the MainHUD dynamic like the rest of the buttons? Other than that, looks good

**Review by KyroVibe — APPROVED** [review]
Love it, looks and feels fantastic!

**Pull request merged**
