### PR TITLE
Move UI elements to their own directory

### PR DESCRIPTION
**Pull request by PepperLola**
Moved components, modals, panels to `src/ui` and added path aliases to `tsconfig.json` and `vite.config.ts` to reference new paths.
> [!NOTE]
> ```
> @/components/* -> src/ui/components/*
> @/modals/*     -> src/ui/modals/*
> @/panels/*     -> src/ui/panels/*

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1650)

### CODE REVIEW

**Review by HunterBarclay — APPROVED** [review]
Looks good!

**Review by BrandonPacewic — APPROVED** [review]
We should make a note about the linting warnings related to fast refresh. We are exporting both functions and components from the same file which breaks fast refresh.

https://github.com/Autodesk/synthesis/blob/541df477edfb0cc623be0842f61689e561abd48e/fission/src/ThemeContext.tsx#L36C1-L42C2

https://github.com/Autodesk/synthesis/blob/541df477edfb0cc623be0842f61689e561abd48e/fission/src/ThemeContext.tsx#L52C1-L52C97

However this is completely unrelated to this PR.

Approved, nice quick and clean!

Edit: Not sure why the code snippet links are not displaying properly 🤔

**Comment by HunterBarclay** [comment]
@BrandonPacewic We have some other larger issues with fast refresh as well. I added a [JIRA bug](https://jira.autodesk.com/browse/AARD-1706) to the backlog.

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic We have some other larger issues with fast refresh as well. I added a [JIRA bug](https://jira.autodesk.com/browse/AARD-1706) to the backlog.

Noted.

**Pull request merged**
