### PR TITLE
Populate Settings Panel with settings

### PR DESCRIPTION
**Pull request by victorxheng**
The settings panel now has a series of settings that the player can modify for their own preference. The look will be updated when the figma mockups come out.

image

Settings are either dropdowns or toggles. 

Three screen modes will be: full screen, maximized window, or windowed. There doesn't seem to be much of a difference between maximized window and full screen, I could consider only leaving full screen and windowed.

Currently, the player can only change the resolution when in windowed mode. Otherwise, the resolution is set to the native resolution. The resolution options change based on changing screen sizes, and if the player selected an option that is the native resolution, when screen resolution changes, it will automatically change to the max resolution for them. 

Currently, a bool called useImperial in the Preference static class is what is changed when the user swaps from imperial to metric. 

In Analytics, the PostDate() function is modified when the user turns off data gathering.

### CODE REVIEW

**Comment by KyroVibe** [comment]
image
Changed a lot of the visual aspects of the panel. Also integrated it with the Layout Manager by making the SettingsPanel script actually inherit panel. Still have to check how it's spawned in and verify saving works. @victorxheng It looks like when you hit the reset button, it doesn't update any of the fields until after you exit the panel and re open it. Also you should add a way of detecting if there have been changes to any of the fields and to only make the Save button usable when changes are detected.

**Review by KyroVibe — CHANGES_REQUESTED** [review]
Make it so the reset button will actually modify the current values in the panel (You can jank this by just closing and reopening the panel). Make it so the save button is disabled when nothing has changed. Make sure the button to open the settings panel uses the LayoutManager. Give your own pass on the styling of the UI (or use the one panel in the figma mock up to style it)

**Comment by victorxheng** [comment]
Changes made

**Review by KyroVibe — CHANGES_REQUESTED** [review]
Can you make it so the screen resolutions are available if windows mode is selected but not saved?

**Comment by victorxheng** [comment]
image

New panel design matching figma.

**Comment by victorxheng** [comment]
@KyroVibe looks good. Merge?

**Comment by victorxheng** [comment]
Merged successfully. Added the API implementation script that was causing errors.

**Comment by victorxheng** [comment]
Ready to merge

**Comment by KyroVibe** [comment]
> 
> 
> Ready to merge

Please resolve the merge conflicts

**Review by matthew17754 — APPROVED** [review]

**Review by KyroVibe — APPROVED** [review]
Looks good

**Pull request merged**
