### PR TITLE
UI Components

### PR DESCRIPTION
**Pull request by PepperLola**
Converted many components to use the [MUI (Base)](https://mui.com/base-ui/) library.

Changes
- Converted to customized MUI components for better functionality and accessibility
- Block interactions behind modals (and add click-away listener to close the modal)
- Customizable starting positions and side padding for panels
- Fixed panel background/height
- Configured formatter and formatted all files

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1669)

### CODE REVIEW

**Review by HunterBarclay — CHANGES_REQUESTED** [review]
Linter isn't happy. I fixed some that were automatic but there are a few left I'll leave up to you.

**Comment by HunterBarclay** [comment]
@PepperLola Some new error when running build:
```
src/components/SelectButton.tsx:53:17 - error TS2322: Type '{ value: string; colorClass: string | undefined; size: ButtonSize | undefined; onClick: () => void; className: string | undefined; }' is not assignable to type 'IntrinsicAttributes & ButtonProps'.
  Property 'colorClass' does not exist on type 'IntrinsicAttributes & ButtonProps'.

53                 colorClass={selecting ? "bg-background-secondary" : colorClass}
  
```

**Review by HunterBarclay — APPROVED** [review]
Looks good!

**Review by a-crowell — APPROVED** [review]
Great work!

**Pull request merged**
