### PR TITLE
List highlighting

### PR DESCRIPTION
**Pull request by ambercmerrill**
Mostly not tied to existing jira issues, but:

Changed highlight color on the scrollable lists so there's a clear difference between the selected one (orange) and the one the user is hovering over (now gray). All the lists I know of are:
- main menu: select a field
- main menu: select a robot
- main menu: view replays
- simulator: change robot (exported)
- simulator: change field

Also changed the inactive color of the sensor output panel close button to match the UI standards (it was the wrong gray).

And changed all the close buttons in the scene from "X" text to icons (issue AARD-898).

### CODE REVIEW

**Comment by ambercmerrill** [comment]
Adding more scene changes so don't merge this yet

**Comment by HiceS** [comment]
say when

**Comment by ambercmerrill** [comment]
Ok now @BradenMccoy should test again to make sure I got all the close buttons

**Comment by ambercmerrill** [comment]
Adding more scene changes

**Pull request merged**
