### PR TITLE
AARD-1685: Joint Config Panel

### PR DESCRIPTION
**Pull request by BrandonPacewic**
- [x] Created a new exporter tab containing all joint configuration options.
- [x] Integrated wheel options within the joint tab for `Revolute` joints.
- [x] Moved all event listeners' 'handle' dealing with updates of the joint panel into a seperate file.
- [x] Joint settings now correctly load and save from `ExporterOptions` as implemented in #981.
- Added several quality of life things for dealing with the joint panel:
  - [x] Adding a joint that is already added will now prompt for removal of selected joint before actually removing it.
  - [x] Added a cancel button to escape out of joint selection mode.
- And, of course, small refactors here and there related to these changes as a part of ongoing exporter refactors ([AARD-1719](https://jira.autodesk.com/browse/AARD-1719)).
  - I say small refactors but this one was rather large.

[JIRA Issue](https://jira.autodesk.com/browse/AARD-1685)

### CODE REVIEW

**Comment by HunterBarclay** [comment]
Ran into an error when exporting

image

There was no info in the log file

**Review by HunterBarclay — CHANGES_REQUESTED** [review]
See error above

**Comment by BrandonPacewic** [comment]
@HunterBarclay Can I get the steps to reproduce this and or have you tell me what the local variables look like in the debugger before going into `SaveFiledialog(...)`. I think I know why this happened but I would like to confirm.

Edit:
By steps to reproduce I mostly mean I can't get this to occur on my machine. I know that you likely just exported dozer.

**Comment by HunterBarclay** [comment]
@BrandonPacewic I made all the joints in dozer wheels, and then made the speed for Left1 and Right1 90. Then clicked export.

**Comment by HunterBarclay** [comment]
image

**Comment by HunterBarclay** [comment]
image

**Comment by HunterBarclay** [comment]
Looks like `fileLocation` is `None`, but so is `joints`?

**Comment by BrandonPacewic** [comment]
@HunterBarclay Blocked on this bug as I cannot recreate it.

**Comment by BrandonPacewic** [comment]
The issue was related to @HunterBarclay 's `HOME` directory not existing somehow. This paired with the `ExporterOptions` object being reset as you have a version of Dozer that does not have the new `isWheel` boolean saved within the design caused it to crash. Everything in the chain now can handle receiving a value of `None`. I could not reproduce this because both my computers don't have this obscure problem. Love it 🙃

**Review by azaleacolburn — COMMENTED** [review]
Maybe the text in the boxes with the sliders could be smaller, or given more space. The sliders make it difficult to read.
Screenshot 2024-07-15 at 10 17 37 AM
Also, for some reason, I can't get all the signal types the toggle, only the ones that currently aren't pwm. 
Screenshot 2024-07-15 at 10 22 28 AM

**Comment by BrandonPacewic** [comment]
@Ewie21 

> Maybe the text in the boxes with the sliders could be smaller, or given more space. The sliders make it difficult to read.

The whole panel can be expanded by dragging it horizontally. For some reason vertical scaling is broken but horizontal works just fine.

Perhaps I could add something to automatically resize the panel?

> Also, for some reason, I can't get all the signal types the toggle, only the ones that currently aren't pwm.

Not sure what you mean by this. There are three different signal types so it should become a drop down when you click on each one. Maybe this is fixed if you resize the panel to be larger horizontally so I never ran into this?

**Comment by azaleacolburn** [comment]
> @Ewie21
> 
> > Maybe the text in the boxes with the sliders could be smaller, or given more space. The sliders make it difficult to read.
> 
> The whole panel can be expanded by dragging it horizontally. For some reason vertical scaling is broken but horizontal works just fine.
> 
> Perhaps I could add something to automatically resize the panel?
> 
> > Also, for some reason, I can't get all the signal types the toggle, only the ones that currently aren't pwm.
> 
> Not sure what you mean by this. There are three different signal types so it should become a drop down when you click on each one. Maybe this is fixed if you resize the panel to be larger horizontally so I never ran into this?

👍  Got it

**Review by HunterBarclay — CHANGES_REQUESTED** [review]
Everything works perfect... except for one seemingly unrelated thing. When I was exporting the Kiwi drive, after exporting once and then reopening to see if the settings have saved, I noticed that when the export command is open, if I hover over the chassis of the bot, it changes my cursor to the select cursor (that you get when adding game pieces and joints)

**Review by azaleacolburn — APPROVED** [review]
We need to make a ticket for making the config command panel bigger by default to make sure the buttons all always work. Great Work! LGTM!

**Review by PepperLola — APPROVED** [review]
Looks like it works, and I got the default utility knife design into Synthesis.

Screenshot 2024-07-18 at 3 12 45 PM

**Review by HunterBarclay — APPROVED** [review]

**Pull request merged**
