### PR TITLE
Match End Options Restore

### PR DESCRIPTION
**Pull request by HunterBarclay**
@LucaHaverty , Please confirm that this restores the changes.

### CODE REVIEW

**Comment by KyroVibe** [comment]
@PepperLola Please readd any changes that were made in the Match State Flow PR that were changed here

**Comment by PepperLola** [comment]
I just merged it but it looks like it works now

**Comment by LucaHaverty** [comment]
> @LucaHaverty , Please confirm that this restores the changes.

Yep, looks good!

**Review by LucaHaverty — APPROVED** [review]
Everything seems properly resorted!

**Review by BrandonPacewic — APPROVED** [review]

**Comment by KyroVibe** [comment]
> When you canceled from robot selection in the past, did it take users back to menu?
> 
> Also bug image attached, but this was probably here before. Happens when you cancel during robot selection, exit to main menu, come back into match mode, then play a match. image

Looks like an Audio bug. Could you create a jira bug for it and assign it to Julian for now?

**Comment by a-crowell** [comment]
I think it's more mode management which is already a known issue. If it's not fixed with that, I'll add it to Jira.

**Pull request merged**
